# Generated by Django 2.2 on 2019-08-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('father_name', models.CharField(max_length=70)),
                ('mother_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentName')),
            ],
        ),
    ]
