# Generated by Django 2.2 on 2019-08-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_1', models.IntegerField()),
                ('contact_2', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ClassInfo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentName')),
                ('reference_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.CreateTeacher')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ShiftInfo')),
            ],
        ),
    ]
