# Generated by Django 2.2 on 2019-08-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftinfo',
            old_name='session',
            new_name='section',
        ),
    ]
