# Generated by Django 2.2 on 2019-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='photo',
            field=models.ImageField(upload_to='media/student/'),
        ),
    ]
