# Generated by Django 2.2 on 2019-08-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190805_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='photo',
            field=models.ImageField(upload_to='media/student'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='shift',
            field=models.ForeignKey(default='Shift and Section', on_delete=django.db.models.deletion.CASCADE, to='student.ShiftInfo'),
        ),
    ]
